# Generated by Django 3.0.5 on 2020-05-07 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('queue_id', models.AutoField(primary_key=True, serialize=False)),
                ('queue_title', models.CharField(max_length=100, verbose_name='название очереди')),
                ('queue_group', models.IntegerField(max_length=7, verbose_name='номер группы')),
                ('queue_info', models.TextField(verbose_name='дополнительная информация')),
                ('queue_create_date', models.DateTimeField(verbose_name='дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20, verbose_name='имя пользователя')),
                ('user_surname', models.CharField(max_length=20, verbose_name='фамилия пользователя')),
                ('user_fathername', models.CharField(max_length=20, verbose_name='отчество пользователя')),
                ('user_type', models.CharField(max_length=20, verbose_name='тип пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='UserInQueue',
            fields=[
                ('uiq_id', models.AutoField(primary_key=True, serialize=False)),
                ('uiq_user_id', models.IntegerField(verbose_name='id пользователя')),
                ('uiq_info', models.TextField(verbose_name='дополнительная информация')),
                ('uiq_queue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_queue.Queue')),
            ],
        ),
    ]
