# Generated by Django 3.0.5 on 2020-05-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_queue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='queue_group',
            field=models.IntegerField(verbose_name='номер группы'),
        ),
    ]
