# Generated by Django 3.0.5 on 2020-05-07 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_queue', '0002_auto_20200507_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queue',
            options={'verbose_name': 'Queue', 'verbose_name_plural': 'Queues'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='userinqueue',
            options={'verbose_name': 'User in queue', 'verbose_name_plural': 'Users in queues'},
        ),
    ]
