# Generated by Django 3.0.5 on 2020-05-07 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_queue', '0003_auto_20200507_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='queue_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='userinqueue',
            old_name='uiq_id',
            new_name='id',
        ),
    ]
