# Generated by Django 3.0.5 on 2020-05-07 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_queue', '0004_auto_20200507_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='id',
            new_name='queue_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='queue_id',
        ),
        migrations.RenameField(
            model_name='userinqueue',
            old_name='id',
            new_name='queue_id',
        ),
    ]
