# Generated by Django 3.0.5 on 2020-05-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_queue', '0006_auto_20200509_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_group',
            field=models.IntegerField(verbose_name='группа пользователя'),
        ),
    ]
