# Generated by Django 3.0.5 on 2020-05-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_queue', '0008_auto_20200510_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinqueue',
            name='uiq_want_to_swap',
            field=models.BooleanField(blank=True, default=False, verbose_name='хочет ли поменяться местами'),
        ),
    ]
