# Generated by Django 3.0.5 on 2020-05-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_queue', '0009_userinqueue_uiq_want_to_swap'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinqueue',
            name='uiq_index',
            field=models.IntegerField(default=0, verbose_name='порядковый номер в очереди'),
        ),
    ]
