# Generated by Django 3.0.5 on 2020-05-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_queue', '0010_userinqueue_uiq_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='queue_create_date',
            field=models.DateTimeField(blank=True, verbose_name='дата создания'),
        ),
    ]
