# Generated by Django 3.0.5 on 2020-05-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_queue', '0011_auto_20200511_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='queue_create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
    ]
