# Generated by Django 3.0.5 on 2020-05-14 19:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lab_queue', '0013_queue_queue_enter_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='queue_enter_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 14, 19, 29, 57, 671940, tzinfo=utc), verbose_name='дата и время открытия очереди'),
        ),
    ]
