# Generated by Django 3.0.5 on 2020-05-14 20:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lab_queue', '0014_auto_20200514_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='queue_enter_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 20, 51, 47, 564521, tzinfo=utc), verbose_name='дата и время открытия очереди'),
        ),
    ]
