# Generated by Django 3.0.5 on 2020-05-18 19:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lab_queue', '0015_auto_20200514_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='queue_enter_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 19, 3, 1, 70794, tzinfo=utc), verbose_name='дата и время открытия очереди'),
        ),
    ]
