# Generated by Django 3.0.5 on 2020-05-18 19:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lab_queue', '0016_auto_20200518_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='queue_enter_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 19, 4, 56, 330157, tzinfo=utc), verbose_name='дата и время открытия очереди'),
        ),
    ]
