# Generated by Django 3.0.5 on 2020-05-18 21:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_queue', '0018_auto_20200518_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='queue_priorities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=list, size=None),
        ),
    ]
