# Generated by Django 3.0.5 on 2020-05-19 14:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_queue', '0019_queue_queue_priorities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='queue_priorities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=None),
        ),
    ]
