# Generated by Django 3.0.5 on 2020-05-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_queue', '0020_auto_20200519_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='queue_info',
            field=models.TextField(blank=True, verbose_name='дополнительная информация'),
        ),
    ]
