# Generated by Django 3.0.5 on 2020-05-19 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lab_queue', '0021_auto_20200519_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='queue_enter_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='дата и время открытия очереди'),
        ),
    ]
