# Generated by Django 3.0.5 on 2020-05-19 18:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_queue', '0023_auto_20200519_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='queue_sort_by_enter_time',
            field=models.BooleanField(blank=True, default=False, verbose_name='сортировать по времени вхождения'),
        ),
        migrations.AddField(
            model_name='userinqueue',
            name='uiq_priorities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=None),
        ),
    ]
