# Generated by Django 3.0.5 on 2020-05-19 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_queue', '0024_auto_20200519_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='queue_sort_by_enter_time',
        ),
    ]
