# Generated by Django 3.0.5 on 2020-05-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_queue', '0025_remove_queue_queue_sort_by_enter_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='queue_sort_by_enter_time',
            field=models.BooleanField(blank=True, default=False, verbose_name='сортировать по времени вхождения'),
        ),
    ]
