# Generated by Django 3.0.5 on 2020-05-20 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab_queue', '0026_queue_queue_sort_by_enter_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_queue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_queue.Queue')),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_user_id', models.IntegerField(verbose_name='id отправителя')),
                ('message_text', models.CharField(blank=True, default='', max_length=1000, verbose_name='текст сообщения')),
                ('message_date', models.DateTimeField(auto_now_add=True, verbose_name='дата отправления')),
                ('message_chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_queue.Chat')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
