# Generated by Django 3.0.5 on 2020-05-30 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_queue', '0028_emailconfirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailconfirmed',
            old_name='hashkey',
            new_name='user_activation_key',
        ),
    ]
