# Generated by Django 3.0.5 on 2020-05-30 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_queue', '0029_auto_20200530_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailconfirmed',
            options={'verbose_name': 'Email Confirmed', 'verbose_name_plural': 'Emails Confirmed'},
        ),
    ]
