# Generated by Django 3.0.5 on 2020-06-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_queue', '0030_auto_20200530_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emailconfirmed',
            name='user_activation_key',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='queue',
            name='queue_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userinqueue',
            name='queue_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
