# Generated by Django 3.0.5 on 2020-06-03 21:11

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_queue', '0031_auto_20200603_2317'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chat',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['chat_id'], name='lab_queue_c_chat_id_8c7cf7_brin'),
        ),
        migrations.AddIndex(
            model_name='emailconfirmed',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['user_activation_key'], name='lab_queue_e_user_ac_8fa7d9_brin'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['message_id'], name='lab_queue_m_message_8654a7_brin'),
        ),
        migrations.AddIndex(
            model_name='queue',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['queue_id'], name='lab_queue_q_queue_i_c41160_brin'),
        ),
        migrations.AddIndex(
            model_name='userinqueue',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['queue_id'], name='lab_queue_u_queue_i_c0859f_brin'),
        ),
    ]
